FROM debian:stretch-slim

RUN groupadd -r bitcoin && useradd -r -m -g bitcoin bitcoin

RUN set -ex \
	&& apt-get update \
	&& apt-get install -qq --no-install-recommends ca-certificates dirmngr gosu gpg wget \
	&& rm -rf /var/lib/apt/lists/*

ENV BITCOIN_VERSION <%= version %>
ENV BITCOIN_URL <%= url %>
ENV BITCOIN_SHA256 <%= sha256 %>
<% if asc_url -%>
ENV BITCOIN_ASC_URL <%= asc_url %>
ENV BITCOIN_PGP_KEY <%= key %>

# retreive pgp key
RUN set -ex \
	&& wget -qO ~/sks-pool.pem https://sks-keyservers.net/sks-keyservers.netCA.pem \
	&& mkdir ~/.gnupg \
	&& chmod 700 ~/.gnupg \
	&& echo 'hkp-cacert ~/sks-pool.pem' >> ~/.gnupg/dirmngr.conf \
	&& gpg --keyserver hkps://hkps.pool.sks-keyservers.net --recv-keys $BITCOIN_PGP_KEY
<% end -%>

# install bitcoin binaries
RUN set -ex \
	&& BITCOIN_DIST=$(basename $BITCOIN_URL) \
	&& wget -qO $BITCOIN_DIST $BITCOIN_URL \
	&& echo "$BITCOIN_SHA256 $BITCOIN_DIST" | sha256sum -c - \
<% if asc_url -%>
	&& wget -qO bitcoin.asc $BITCOIN_ASC_URL \
	&& gpg --verify bitcoin.asc \
<% end -%>
	&& tar -xzvf $BITCOIN_DIST -C /usr/local --strip-components=1 --exclude=*-qt \
	&& rm bitcoin*

ENV BITCOIN_DATA /data
RUN mkdir $BITCOIN_DATA \
	&& chown bitcoin:bitcoin $BITCOIN_DATA \
	&& ln -s $BITCOIN_DATA /home/bitcoin/.bitcoin
VOLUME /data

COPY docker-entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 8332 8333 18332 18333
CMD ["bitcoind"]
